### PR TITLE
Bugfix/support for custom addons

### PR DESCRIPTION
**Pull request by viktor-yengovatov**

### CODE REVIEW

**Comment by mlytvyn** [comment]
@viktor-yengovatov , thank you very much for your contribution!
Can you please provide some details of the changes, maybe screenshots, etc.? It will help other users of the Plugin to take all advantages of the new features.

**Comment by viktor-yengovatov** [comment]
@mlytvyn , The bug was that custom submodule extensions, like addons were not included into the modules, sources were not indexed nor compiled.
The issue existed for submodules like `commonweb` and `acceleratoraddon`.

**Comment by mlytvyn** [comment]
@viktor-yengovatov , can we sync-up in Telegram on this topic? We may need to adjust `RegularContentRootConfigurator` and other configurators.
For `acceleratoraddon` -> `web/src` is registered as content root in my test setup.

Feel free to drop me a message: `lytvyn.michael@gmail.com`

**Comment by viktor-yengovatov** [comment]
I suggest to keep this PR open or reject.
Seems still work is needed due to dependency issues among the web addons.

In order to call I have to have clean vanilla setup with reproducible issue. Need time for that.

**Pull request closed without merging**
